import { CraneCategory } from "./types";

export const craneCategories: CraneCategory[] = [
  {
    id: "atc",
    title: "All-Terrain Cranes (ATC)",
    href: "atc",
    description:
      "Versatile cranes designed for both on-road and off-road operations with exceptional mobility and lifting capacity. Our fleet includes premium Liebherr and Demag models ranging from 65 to 500 tons.",
    image: "/ATC.jpg",
    cranes: [
      {
        name: "LTM 1120",
        capacity: "70 ton",
        year: "1991 & other years",
        manufacturer: "Liebherr",
        image: "/atc/LTM-1120.jpg",
      },
      {
        name: "LTM 1100",
        capacity: "65 ton",
        year: "1994",
        manufacturer: "Liebherr",
        image: "/atc/LTM-1100.jpg",
      },
      {
        name: "LTM 1300",
        capacity: "300 ton",
        year: "2002",
        manufacturer: "Liebherr",
        image: "/atc/LTM-1300.jpg",
      },
      {
        name: "LTM 1300/1",
        capacity: "300 ton",
        year: "2001",
        manufacturer: "Liebherr",
        image: "/atc/LTM-1300-1.jpg",
      },
      {
        name: "LTM 1500-8.1",
        capacity: "500 ton",
        year: "2002",
        manufacturer: "Liebherr",
        image: "/atc/LTM-1500-8.1.jpg",
      },
      {
        name: "AC 200-1",
        capacity: "250 ton",
        year: "2005",
        manufacturer: "Demag",
        image: "/atc/AC-200-1.jpg",
      },
      {
        name: "AC 100",
        capacity: "100 ton",
        year: "2007",
        manufacturer: "Demag",
        image: "/atc/AC-100.jpg",
      },
    ],
  },
  {
    id: "tc",
    title: "Truck Cranes (TC)",
    href: "tc",
    description:
      "Mobile cranes mounted on truck chassis for quick deployment and transportation between job sites. Featuring reliable XCMG and Iveco models for efficient project execution.",
    image: "/TC.jpg",
    cranes: [
      {
        name: "QY25K",
        capacity: "25 ton",
        year: "multiple years",
        manufacturer: "XCMG",
        image: "/tc/QY25K.webp",
      },
      {
        name: "QY50B",
        capacity: "50 ton",
        year: "multiple years",
        manufacturer: "XCMG",
        image: "/tc/QY50B.jpg",
      },
      {
        name: "QY65K",
        capacity: "65 ton",
        year: "multiple years",
        manufacturer: "XCMG",
        image: "/tc/QY65K.jpg",
      },
      {
        name: "QY70K",
        capacity: "70 ton",
        year: "multiple years",
        manufacturer: "XCMG",
        image: "/tc/QY70K.jpg",
      },
      {
        name: "180 E 28",
        capacity: "Truck-mounted",
        year: "N/A",
        manufacturer: "Iveco",
        image: "/tc/180-E-28.jpg",
      },
    ],
  },
  {
    id: "rtc",
    title: "Rough Terrain Cranes (RTC)",
    href: "rtc",
    description:
      "Specialized cranes built for challenging off-road conditions with enhanced stability and mobility. Our Terex models provide reliable performance in the most demanding environments.",
    image: "/RTC.jpg",
    cranes: [
      {
        name: "RT 555",
        capacity: "30 ton",
        year: "2007",
        manufacturer: "Terex",
        image: "/rtc/RT-555.jpg",
      },
      {
        name: "RT 555-1",
        capacity: "55 ton",
        year: "2007",
        manufacturer: "Terex",
        image: "/rtc/RT-555-1.jpg",
      },
    ],
  },
  {
    id: "crawler",
    title: "Crawler Cranes",
    href: "crawler",
    description:
      "Heavy-duty cranes with tracked undercarriages for maximum stability and lifting capacity on challenging terrain. From 50 to 320 tons, our crawler fleet handles the most complex lifting operations.",
    image: "/CRAWLER.jpg",
    cranes: [
      {
        name: "SCC1000",
        capacity: "100 ton",
        year: "2008",
        manufacturer: "Sany",
        image: "/crawler/SCC1000.jpg",
      },
      {
        name: "SCC500D",
        capacity: "50 ton",
        year: "2007",
        manufacturer: "Sany",
        image: "/crawler/SCC500D.jpg",
      },
      {
        name: "SCC3200",
        capacity: "320 ton",
        year: "2008",
        manufacturer: "Sany",
        image: "/crawler/SCC3200.webp",
      },
      {
        name: "QUY70",
        capacity: "70 ton",
        year: "2007, 2003",
        manufacturer: "Zoomlion",
        image: "/crawler/QUY70.webp",
      },
      {
        name: "SCX2500",
        capacity: "250 ton",
        year: "2005",
        manufacturer: "Hitachi Sumitomo",
        image: "/crawler/SCX2500.jpg",
      },
      {
        name: "LR 1280",
        capacity: "200 ton",
        year: "1993",
        manufacturer: "Liebherr",
        image: "/crawler/LR-1280.jpeg",
      },
      {
        name: "HS843HD",
        capacity: "100 ton",
        year: "2003",
        manufacturer: "Liebherr",
        image: "/crawler/HS843HD.jpg",
      },
      {
        name: "6100",
        capacity: "100 ton",
        year: "1999",
        manufacturer: "Sennebogen",
        image: "/crawler/6100.jpg",
      },
      {
        name: "CH135",
        capacity: "135 ton",
        year: "N/A",
        manufacturer: "Ruston Bucyrus",
        image: "/crawler/CH135.jpg",
      },
      {
        name: "CCH",
        capacity: "120 ton",
        year: "1991",
        manufacturer: "IHI",
        image: "/crawler/CCH.jpg",
      },
      {
        name: "LS 248 H",
        capacity: "100 ton",
        year: "1987",
        manufacturer: "Link-Belt",
        image: "/crawler/LS-248-H.jpg",
      },
      {
        name: "MC136",
        capacity: "55 ton",
        year: "1990",
        manufacturer: "Hyco",
        image: "/crawler/MC136.jpg",
      },
    ],
  },
  {
    id: "special",
    title: "Mobile Harbour & Special Equipment",
    href: "special",
    description:
      "Specialized equipment including mobile harbour cranes and versatile lifting solutions for unique applications. Our Grove models provide exceptional performance in specialized environments.",
    image: "/MOBILE.jpg",
    cranes: [
      {
        name: "GMK 5130",
        capacity: "130 ton",
        year: "1998",
        manufacturer: "Grove",
        image: "/special/GMK-5130.jpg",
      },
      {
        name: "GMK 5100",
        capacity: "100 ton",
        year: "2003",
        manufacturer: "Grove",
        image: "/special/GMK-5100.jpg",
      },
      {
        name: "GMK 3050",
        capacity: "50 ton",
        year: "1999, 2000",
        manufacturer: "Grove",
        image: "/special/GMK-3050.jpg",
      },
    ],
  },
  {
    id: "equipment",
    title: "Supporting Equipment",
    href: "support",
    description:
      "Essential support equipment including trailers, manlifts, and tractors to complete your project requirements. Complete solutions for comprehensive project support.",
    image: "/SUPPORT.jpg",
    cranes: [
      {
        name: "Lowbed Trailers",
        capacity: "Various capacities",
        year: "Multiple years",
        manufacturer: "Scheuerle, Welte",
        image: "/support/Lowbed-Trailers.jpg",
      },
      {
        name: "DAF 2100",
        capacity: "Manlift",
        year: "N/A",
        manufacturer: "DAF",
        image: "/support/DAF-2100.jpg",
      },
      {
        name: "Mercedes",
        capacity: "Tractor",
        year: "N/A",
        manufacturer: "Mercedes",
        image: "/support/Mercedes.jpeg",
      },
    ],
  },
];
